server:
<<<<<<< HEAD
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/teste?createDatabaseIfNotExist=true
=======
  port: 8085
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mercado?createDatabaseIfNotExist=true
>>>>>>> 8dd4299 (implementa Venda e VendaRepository)
    username: iuri
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update